// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.bitoc.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StringPair extends Table {
  public static StringPair getRootAsStringPair(ByteBuffer _bb) { return getRootAsStringPair(_bb, new StringPair()); }
  public static StringPair getRootAsStringPair(ByteBuffer _bb, StringPair obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StringPair __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String value() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createStringPair(FlatBufferBuilder builder,
      int keyOffset,
      int valueOffset) {
    builder.startObject(2);
    StringPair.addValue(builder, valueOffset);
    StringPair.addKey(builder, keyOffset);
    return StringPair.endStringPair(builder);
  }

  public static void startStringPair(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static int endStringPair(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // key
    builder.required(o, 6);  // value
    return o;
  }
}

